/**
 * Public course catalog — bilingual source of truth.
 * Served as the Next.js mock fallback and mirrored by StudentPortalSeeder.
 *
 * Cover images: high-resolution Unsplash stills in the same visual family as
 * PM-Tricks course cards (live classroom, self-paced video, exam prep).
 */

export const CATALOG_CATEGORIES = ['all', 'live', 'recorded', 'simulators', 'materials'];

export const INSTRUCTOR = {
  name_en: 'Dr. Talaat El-Awady',
  name_ar: 'د. طلعت العوضي',
  title_en: 'ATP Certified PMP Trainer',
  title_ar: 'مدرب PMP معتمد من ATP',
  photo: '/images/DR.jpg',
  trained: '2,000+',
  countries: 16,
  credentials_en: [
    'PMI Authorized Training Partner (ATP) Instructor',
    'PMP®, PMI-RMP®, PMI-ACP®',
    '2,000+ professionals trained across 16 countries',
  ],
  credentials_ar: [
    'مدرب معتمد من شريك التدريب الرسمي لمعهد PMI',
    'PMP® و PMI-RMP® و PMI-ACP®',
    'درّب أكثر من 2,000 محترف في 16 دولة',
  ],
  bio_en:
    'Dr. Talaat El-Awady is an ATP-certified trainer who has coached project leaders across the Middle East, Africa, and Southeast Asia. His programs combine PMBOK® 8th Edition, real exam heuristics, and practical AI tools for modern delivery teams.',
  bio_ar:
    'د. طلعت العوضي مدرب معتمد من ATP درّب قادة المشاريع في الشرق الأوسط وأفريقيا وجنوب شرق آسيا. تجمع برامجه بين الدليل المعرفي PMBOK® الإصدار الثامن، وتقنيات تفكيك أسئلة الامتحان، وأدوات الذكاء الاصطناعي العملية لفرق التنفيذ الحديثة.',
};

const CHECKLIST_LIVE_EN = [
  '60-day study plan',
  'Exam simulator access',
  'WhatsApp support group',
  '60 contact hours certificate',
  'LinkedIn optimization guide',
];
const CHECKLIST_LIVE_AR = [
  'خطة دراسة لـ 60 يومًا',
  'الوصول لمحاكي الامتحان',
  'مجموعة دعم واتساب',
  'شهادة 60 ساعة اتصال',
  'دليل تحسين ملف لينكدإن',
];

export const PUBLIC_CATALOG = [
  {
    slug: 'pmp-live-training',
    category: 'live',
    defaultMode: 'live',
    availableModes: ['live', 'recorded'],
    badge_en: 'Live & Interactive',
    badge_ar: 'مباشر وتفاعلي',
    title_en: 'PMP® Live Training Full Program',
    title_ar: 'البرنامج الكامل لتدريب PMP® المباشر',
    subtitle_en: 'Live virtual classroom + recorded library for first-time PMP success.',
    subtitle_ar: 'قاعة افتراضية مباشرة مع مكتبة مسجّلة لاجتياز PMP من المحاولة الأولى.',
    description_en:
      'An intensive live program built for working professionals who want instructor-led accountability. You join 25 hours of interactive virtual sessions, 35 hours of recorded masterclasses, and weekly Q&A until exam day. Every module maps to PMBOK® 8th Edition domains, with question-breakdown labs and an AI-in-PM workshop so you leave ready for both the exam and the job.',
    description_ar:
      'برنامج مباشر مكثف للمهنيين العاملين الذين يريدون التزامًا مع مدرّب. تنضم إلى 25 ساعة جلسات افتراضية تفاعلية، و35 ساعة محاضرات مسجّلة، وجلسات أسئلة وأجوبة أسبوعية حتى يوم الامتحان. كل محور مربوط بنطاقات PMBOK® الإصدار الثامن، مع مختبرات تفكيك الأسئلة وورشة الذكاء الاصطناعي في إدارة المشاريع.',
    price: 599,
    original_price: 799,
    currency: 'USD',
    rating: 4.9,
    students_count: 18420,
    duration_hours: 60,
    duration_label_en: '60 Hours',
    duration_label_ar: '60 ساعة',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-06-12',
    cover_image:
      'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'Project managers preparing for PMP® certification',
      'Engineers and team leads who own delivery outcomes',
      'PMO staff seeking 60 contact hours and exam strategy',
    ],
    target_audience_ar: [
      'مديرو المشاريع المستعدون لشهادة PMP®',
      'المهندسون وقادة الفرق المسؤولون عن نتائج التسليم',
      'فريق مكتب إدارة المشاريع الباحث عن 60 ساعة اتصال واستراتيجية الامتحان',
    ],
    learning_outcomes_en: [
      'Apply PMBOK® 8th Edition domains to live project scenarios',
      'Break down situational exam questions under timed pressure',
      'Use AI copilots ethically inside planning, risk, and reporting',
      'Build a 60-day study cadence that survives a full-time job',
      'Lead stakeholder conversations with Agile and predictive hybrids',
    ],
    learning_outcomes_ar: [
      'تطبيق نطاقات PMBOK® الإصدار الثامن على سيناريوهات مشاريع حقيقية',
      'تفكيك أسئلة الامتحان الموقفية تحت ضغط الوقت',
      'استخدام مساعدات الذكاء الاصطناعي بأخلاقيات في التخطيط والمخاطر والتقارير',
      'بناء إيقاع دراسة لـ 60 يومًا يناسب العمل بدوام كامل',
      'قيادة حوارات أصحاب المصلحة بأسلوب هجين بين الرشيق والتنبؤي',
    ],
    curriculum: [
      {
        title_en: 'Module 1 — People & Leadership',
        title_ar: 'المحور 1 — الأشخاص والقيادة',
        duration_en: '12 hours',
        duration_ar: '12 ساعة',
        lessons_en: ['Servant leadership', 'Conflict & negotiation', 'Team performance'],
        lessons_ar: ['القيادة الخادمة', 'النزاع والتفاوض', 'أداء الفريق'],
      },
      {
        title_en: 'Module 2 — Process & Delivery',
        title_ar: 'المحور 2 — العمليات والتسليم',
        duration_en: '18 hours',
        duration_ar: '18 ساعة',
        lessons_en: ['Hybrid life cycles', 'Scope & schedule', 'Quality & procurement'],
        lessons_ar: ['دورات الحياة الهجينة', 'النطاق والجدول', 'الجودة والمشتريات'],
      },
      {
        title_en: 'Module 3 — Business Environment',
        title_ar: 'المحور 3 — بيئة الأعمال',
        duration_en: '10 hours',
        duration_ar: '10 ساعات',
        lessons_en: ['Benefits realization', 'Compliance', 'Organizational change'],
        lessons_ar: ['تحقيق المنافع', 'الامتثال', 'التغيير المؤسسي'],
      },
      {
        title_en: 'Module 4 — Exam Labs & AI in PM',
        title_ar: 'المحور 4 — مختبرات الامتحان والذكاء الاصطناعي',
        duration_en: '20 hours',
        duration_ar: '20 ساعة',
        lessons_en: ['Question heuristics', 'Full mock exams', 'AI tooling workshop'],
        lessons_ar: ['حدس الأسئلة', 'امتحانات تجريبية كاملة', 'ورشة أدوات الذكاء الاصطناعي'],
      },
    ],
    schedule_en:
      '25 hours live virtual sessions + 35 hours recorded content + weekly Q&A until you sit the exam.',
    schedule_ar:
      '25 ساعة جلسات افتراضية مباشرة + 35 ساعة محتوى مسجّل + جلسات أسئلة وأجوبة أسبوعية حتى دخول الامتحان.',
    modes: {
      live: {
        price: 599,
        original_price: 799,
        duration_en: '60 Hours',
        duration_ar: '60 ساعة',
        features_en: CHECKLIST_LIVE_EN,
        features_ar: CHECKLIST_LIVE_AR,
      },
      recorded: {
        price: 399,
        original_price: 499,
        duration_en: '35 Hours',
        duration_ar: '35 ساعة',
        features_en: [
          'Full recorded masterclass library',
          'Exam simulator (1,200 questions)',
          'Email mentor support',
          '35 PDU / contact-hour certificate',
          'LinkedIn optimization guide',
        ],
        features_ar: [
          'مكتبة المحاضرات المسجّلة كاملة',
          'محاكي امتحان (1,200 سؤال)',
          'دعم المرشد عبر البريد',
          'شهادة 35 ساعة اتصال / PDU',
          'دليل تحسين ملف لينكدإن',
        ],
      },
    },
  },
  {
    slug: 'pmp-recorded-program',
    category: 'recorded',
    defaultMode: 'recorded',
    availableModes: ['recorded'],
    badge_en: 'Self-Paced',
    badge_ar: 'بالوتيرة الذاتية',
    title_en: 'PMP® Full Recorded Program',
    title_ar: 'البرنامج الكامل المسجّل لـ PMP®',
    subtitle_en: 'Watch, rewind, and drill — a complete self-paced PMP path.',
    subtitle_ar: 'شاهد وأعد وشغّل التمارين — مسار PMP كامل بالوتيرة الذاتية.',
    description_en:
      'The recorded program is the same ATP-aligned curriculum as the live cohort, packaged for professionals who need night-and-weekend study. Thirty-five hours of cinematic lessons, downloadable mind maps, and a full exam simulator let you progress without a fixed calendar.',
    description_ar:
      'البرنامج المسجّل هو المنهج نفسه المعتمد من ATP في المجموعة المباشرة، مجهّز للمهنيين الذين يدرسون ليلاً وفي عطلة نهاية الأسبوع. خمس وثلاثون ساعة دروس سينمائية، وخرائط ذهنية قابلة للتحميل، ومحاكي امتحان كامل دون جدول ثابت.',
    price: 399,
    original_price: 399,
    currency: 'USD',
    rating: 4.8,
    students_count: 22150,
    duration_hours: 35,
    duration_label_en: '35 Hours',
    duration_label_ar: '35 ساعة',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-05-28',
    cover_image:
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'Busy professionals who cannot join live cohorts',
      'Repeat exam takers who need structured replay',
      'Teams rolling out a shared PMP study library',
    ],
    target_audience_ar: [
      'المهنيون المشغولون الذين لا يستطيعون الانضمام للمجموعات المباشرة',
      'من يعيد الامتحان ويحتاج إعادة مشاهدة منظمة',
      'الفرق التي تبني مكتبة دراسة مشتركة لـ PMP',
    ],
    learning_outcomes_en: [
      'Master PMBOK® 8th Edition at your own pace',
      'Score 80%+ on domain-level practice sets',
      'Apply Agile, predictive, and hybrid tools on the job',
      'Use AI prompts for charter, WBS, and risk registers',
    ],
    learning_outcomes_ar: [
      'إتقان PMBOK® الإصدار الثامن بوتيرتك الخاصة',
      'تحقيق 80%+ في مجموعات التمرين حسب النطاق',
      'تطبيق أدوات الرشيق والتنبؤي والهجين في العمل',
      'استخدام أوامر الذكاء الاصطناعي للميثاق وهيكل التجزئة وسجل المخاطر',
    ],
    curriculum: [
      {
        title_en: 'Foundations & Mindset',
        title_ar: 'الأساسيات والعقلية',
        duration_en: '6 hours',
        duration_ar: '6 ساعات',
        lessons_en: ['PMP exam map', 'ECO domains', 'Study OS'],
        lessons_ar: ['خريطة امتحان PMP', 'نطاقات ECO', 'نظام الدراسة'],
      },
      {
        title_en: 'People Domain Deep Dive',
        title_ar: 'تعميق نطاق الأشخاص',
        duration_en: '10 hours',
        duration_ar: '10 ساعات',
        lessons_en: ['Leadership styles', 'Team development', 'Communications'],
        lessons_ar: ['أنماط القيادة', 'تطوير الفريق', 'الاتصالات'],
      },
      {
        title_en: 'Process Domain Deep Dive',
        title_ar: 'تعميق نطاق العمليات',
        duration_en: '12 hours',
        duration_ar: '12 ساعة',
        lessons_en: ['Planning toolkit', 'Delivery & control', 'Close-out'],
        lessons_ar: ['أدوات التخطيط', 'التسليم والرقابة', 'الإغلاق'],
      },
      {
        title_en: 'Business + Mock Exams',
        title_ar: 'الأعمال + الامتحانات التجريبية',
        duration_en: '7 hours',
        duration_ar: '7 ساعات',
        lessons_en: ['Strategy alignment', 'Two full mocks', 'Error log method'],
        lessons_ar: ['مواءمة الاستراتيجية', 'امتحانان تجريبيان كاملان', 'أسلوب سجل الأخطاء'],
      },
    ],
    schedule_en: '35 hours of on-demand video. Lifetime access to the current edition.',
    schedule_ar: '35 ساعة فيديو عند الطلب. وصول مدى الحياة للإصدار الحالي.',
    modes: {
      recorded: {
        price: 399,
        original_price: 399,
        duration_en: '35 Hours',
        duration_ar: '35 ساعة',
        features_en: [
          '35-hour recorded academy',
          'Exam simulator access',
          'Downloadable mind maps',
          '35 contact hours certificate',
          'LinkedIn optimization guide',
        ],
        features_ar: [
          'أكاديمية مسجّلة 35 ساعة',
          'الوصول لمحاكي الامتحان',
          'خرائط ذهنية قابلة للتحميل',
          'شهادة 35 ساعة اتصال',
          'دليل تحسين ملف لينكدإن',
        ],
      },
    },
  },
  {
    slug: 'pmp-fast-track',
    category: 'recorded',
    defaultMode: 'recorded',
    availableModes: ['recorded'],
    badge_en: 'Accelerated',
    badge_ar: 'مسار سريع',
    title_en: 'PMP® Fast Track (Recorded)',
    title_ar: 'المسار السريع لـ PMP® (مسجّل)',
    subtitle_en: 'Twenty focused hours for experienced PMs who already know the craft.',
    subtitle_ar: 'عشرون ساعة مركّزة لمديري المشاريع ذوي الخبرة.',
    description_en:
      'Fast Track skips the introductory lectures and goes straight to exam pattern recognition, ECO mapping, and high-yield drills. Ideal if you already run projects and need a compressed, recorded sprint to exam day.',
    description_ar:
      'يتجاوز المسار السريع المحاضرات التمهيدية وينتقل مباشرة إلى تمييز أنماط الامتحان، وربط ECO، والتمارين عالية العائد. مثالي إن كنت تدير مشاريع بالفعل وتحتاج سباقًا مسجّلًا مكثفًا حتى يوم الاختبار.',
    price: 299,
    original_price: 299,
    currency: 'USD',
    rating: 4.7,
    students_count: 9680,
    duration_hours: 20,
    duration_label_en: '20 Hours',
    duration_label_ar: '20 ساعة',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-04-02',
    cover_image:
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1600&q=80',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'Seasoned PMs with 3+ years of delivery experience',
      'Candidates retaking the exam within 90 days',
      'Consultants who need a rapid ECO refresh',
    ],
    target_audience_ar: [
      'مديرو مشاريع متمرسون بخبرة تسليم 3 سنوات فأكثر',
      'المرشحون الذين يعيدون الامتحان خلال 90 يومًا',
      'الاستشاريون الذين يحتاجون تحديثًا سريعًا لـ ECO',
    ],
    learning_outcomes_en: [
      'Compress ECO coverage into a 20-hour sprint',
      'Recognize trap answers in situational items',
      'Build a 21-day revision calendar',
      'Apply AI to generate flash drills from weak domains',
    ],
    learning_outcomes_ar: [
      'ضغط تغطية ECO في سباق 20 ساعة',
      'تمييز الإجابات الفخ في الأسئلة الموقفية',
      'بناء جدول مراجعة لـ 21 يومًا',
      'استخدام الذكاء الاصطناعي لتمارين سريعة من النطاقات الضعيفة',
    ],
    curriculum: [
      {
        title_en: 'Sprint 1 — ECO Compression',
        title_ar: 'السبرنت 1 — ضغط ECO',
        duration_en: '8 hours',
        duration_ar: '8 ساعات',
        lessons_en: ['People hotspots', 'Process hotspots', 'Business hotspots'],
        lessons_ar: ['نقاط الأشخاص الساخنة', 'نقاط العمليات الساخنة', 'نقاط الأعمال الساخنة'],
      },
      {
        title_en: 'Sprint 2 — Question Warfare',
        title_ar: 'السبرنت 2 — حرب الأسئلة',
        duration_en: '8 hours',
        duration_ar: '8 ساعات',
        lessons_en: ['Elimination patterns', 'Agile vs predictive tells', 'Timed sets'],
        lessons_ar: ['أنماط الاستبعاد', 'علامات الرشيق مقابل التنبؤي', 'مجموعات موقوتة'],
      },
      {
        title_en: 'Sprint 3 — Exam Week',
        title_ar: 'السبرنت 3 — أسبوع الامتحان',
        duration_en: '4 hours',
        duration_ar: '4 ساعات',
        lessons_en: ['Full mock', 'Error clinic', 'Test-day protocol'],
        lessons_ar: ['تجريبي كامل', 'عيادة الأخطاء', 'بروتوكول يوم الاختبار'],
      },
    ],
    schedule_en: '20 hours recorded. Designed to finish in 3 consecutive weekends.',
    schedule_ar: '20 ساعة مسجّلة. مصمّم للإنهاء في 3 عطل نهاية أسبوع متتالية.',
    modes: {
      recorded: {
        price: 299,
        original_price: 299,
        duration_en: '20 Hours',
        duration_ar: '20 ساعة',
        features_en: [
          'Accelerated 20-hour syllabus',
          'High-yield question bank',
          '21-day study plan',
          'Exam-week protocol PDF',
          'WhatsApp exam-week desk',
        ],
        features_ar: [
          'منهج مسرّع 20 ساعة',
          'بنك أسئلة عالية العائد',
          'خطة دراسة 21 يومًا',
          'ملف بروتوكول أسبوع الامتحان',
          'مكتب واتساب لأسبوع الامتحان',
        ],
      },
    },
  },
  {
    slug: 'pmi-rmp-program',
    category: 'live',
    defaultMode: 'live',
    availableModes: ['live', 'recorded'],
    badge_en: 'Specialized',
    badge_ar: 'تخصصي',
    title_en: 'PMI-RMP® Risk Management Program',
    title_ar: 'برنامج إدارة المخاطر PMI-RMP®',
    subtitle_en: 'Specialist risk credential for PMs who own uncertainty.',
    subtitle_ar: 'شهادة مخاطر متخصصة لمديري المشاريع المسؤولين عن عدم اليقين.',
    description_en:
      'Go beyond the PMP risk chapter. This PMI-RMP® program covers qualitative and quantitative analysis, risk-adjusted planning, and governance that survives audits. Live labs use real registers from construction, IT, and transformation programs.',
    description_ar:
      'تجاوز فصل المخاطر في PMP. يغطي برنامج PMI-RMP® التحليل النوعي والكمي، والتخطيط المعدّل حسب المخاطر، والحوكمة التي تصمد أمام التدقيق. المختبرات المباشرة تستخدم سجلات حقيقية من الإنشاء وتقنية المعلومات وبرامج التحول.',
    price: 297,
    original_price: 297,
    currency: 'USD',
    rating: 4.85,
    students_count: 6420,
    duration_hours: 30,
    duration_label_en: '30 Hours',
    duration_label_ar: '30 ساعة',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-03-18',
    cover_image:
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'PMP holders specializing in risk or PMO governance',
      'Engineers in construction, oil & gas, and IT delivery',
      'Risk owners who need a PMI-RMP® exam strategy',
    ],
    target_audience_ar: [
      'حاملو PMP المتخصصون في المخاطر أو حوكمة مكتب المشاريع',
      'المهندسون في الإنشاء والنفط والغاز وتسليم تقنية المعلومات',
      'مسؤولو المخاطر الذين يحتاجون استراتيجية امتحان PMI-RMP®',
    ],
    learning_outcomes_en: [
      'Build a living risk register tied to strategy',
      'Run qualitative and quantitative analysis workshops',
      'Design risk-adjusted schedules and reserves',
      'Pass PMI-RMP® with domain-balanced mocks',
    ],
    learning_outcomes_ar: [
      'بناء سجل مخاطر حيّ مربوط بالاستراتيجية',
      'إدارة ورش التحليل النوعي والكمي',
      'تصميم جداول واحتياطيات معدّلة حسب المخاطر',
      'اجتياز PMI-RMP® بتجريبيات متوازنة النطاقات',
    ],
    curriculum: [
      {
        title_en: 'Risk Strategy & Governance',
        title_ar: 'استراتيجية المخاطر والحوكمة',
        duration_en: '8 hours',
        duration_ar: '8 ساعات',
        lessons_en: ['Risk appetite', 'Roles', 'Policy design'],
        lessons_ar: ['قابلية المخاطر', 'الأدوار', 'تصميم السياسة'],
      },
      {
        title_en: 'Identification & Analysis',
        title_ar: 'التحديد والتحليل',
        duration_en: '12 hours',
        duration_ar: '12 ساعة',
        lessons_en: ['Workshops', 'Qualitative scoring', 'Quantitative models'],
        lessons_ar: ['ورش العمل', 'التقييم النوعي', 'النماذج الكمية'],
      },
      {
        title_en: 'Response & Exam',
        title_ar: 'الاستجابة والامتحان',
        duration_en: '10 hours',
        duration_ar: '10 ساعات',
        lessons_en: ['Response playbooks', 'Monitoring', 'RMP mocks'],
        lessons_ar: ['أدلة الاستجابة', 'المراقبة', 'تجريبيات RMP'],
      },
    ],
    schedule_en: '18 hours live workshops + 12 hours recorded labs and mocks.',
    schedule_ar: '18 ساعة ورش مباشرة + 12 ساعة مختبرات وتجاريب مسجّلة.',
    modes: {
      live: {
        price: 297,
        original_price: 397,
        duration_en: '30 Hours',
        duration_ar: '30 ساعة',
        features_en: [
          'Live risk workshops',
          'Quantitative analysis templates',
          'WhatsApp specialist group',
          '30 contact hours certificate',
          'PMI-RMP mock exams',
        ],
        features_ar: [
          'ورش مخاطر مباشرة',
          'قوالب التحليل الكمي',
          'مجموعة واتساب متخصصة',
          'شهادة 30 ساعة اتصال',
          'امتحانات تجريبية PMI-RMP',
        ],
      },
      recorded: {
        price: 247,
        original_price: 297,
        duration_en: '24 Hours',
        duration_ar: '24 ساعة',
        features_en: [
          'Recorded risk academy',
          'Register & tornado templates',
          'Email specialist support',
          '24 contact hours certificate',
          'PMI-RMP mock exams',
        ],
        features_ar: [
          'أكاديمية مخاطر مسجّلة',
          'قوالب السجل ومخطط تورنادو',
          'دعم متخصص عبر البريد',
          'شهادة 24 ساعة اتصال',
          'امتحانات تجريبية PMI-RMP',
        ],
      },
    },
  },
  {
    slug: 'pmp-exam-simulator-pro',
    category: 'simulators',
    defaultMode: 'simulator',
    availableModes: ['simulator'],
    badge_en: 'Exam Prep',
    badge_ar: 'تحضير الامتحان',
    title_en: 'PMP® Exam Simulator Pro',
    title_ar: 'محاكي امتحان PMP® الاحترافي',
    subtitle_en: '1,800+ ECO-aligned questions with full exam timing and analytics.',
    subtitle_ar: 'أكثر من 1,800 سؤال مطابق لـ ECO مع توقيت الامتحان الكامل والتحليلات.',
    description_en:
      'Simulator Pro is a dedicated exam engine: 1,800+ original items, domain analytics, and two 180-question full exams that mimic Pearson Vue constraints. Pair it with any video program or use it as a standalone drill tool in the last 30 days.',
    description_ar:
      'محاكي برو محرك امتحان مخصص: أكثر من 1,800 سؤال أصلي، وتحليلات النطاقات، وامتحانان كاملان بـ 180 سؤالًا يحاكيان قيود Pearson Vue. ادمجه مع أي برنامج فيديو أو استخدمه أداة تدريب مستقلة في آخر 30 يومًا.',
    price: 120,
    original_price: 120,
    currency: 'USD',
    rating: 4.92,
    students_count: 30110,
    duration_hours: 0,
    duration_label_en: '1,800+ Questions',
    duration_label_ar: '+1,800 سؤال',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-07-01',
    cover_image:
      'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1600&q=80',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'Candidates in the final 30 days before the PMP exam',
      'Students who already completed a video program',
      'Study groups that need a shared question bank',
    ],
    target_audience_ar: [
      'المرشحون في آخر 30 يومًا قبل امتحان PMP',
      'الطلاب الذين أكملوا برنامج فيديو مسبقًا',
      'مجموعات الدراسة التي تحتاج بنك أسئلة مشتركًا',
    ],
    learning_outcomes_en: [
      'Build exam stamina across 230 minutes',
      'Isolate weak ECO tasks with heatmaps',
      'Practice bilingual wording used on the real exam',
      'Leave with a personal error-log playbook',
    ],
    learning_outcomes_ar: [
      'بناء قدرة التحمل عبر 230 دقيقة',
      'عزل مهام ECO الضعيفة بخرائط حرارية',
      'التدرّب على الصياغة ثنائية اللغة في الامتحان الحقيقي',
      'الخروج بدليل شخصي لسجل الأخطاء',
    ],
    curriculum: [
      {
        title_en: 'Domain Drills',
        title_ar: 'تمارين النطاقات',
        duration_en: '1,200 questions',
        duration_ar: '1,200 سؤال',
        lessons_en: ['People', 'Process', 'Business environment'],
        lessons_ar: ['الأشخاص', 'العمليات', 'بيئة الأعمال'],
      },
      {
        title_en: 'Full-Length Exams',
        title_ar: 'امتحانات كاملة',
        duration_en: '360 questions',
        duration_ar: '360 سؤالًا',
        lessons_en: ['Mock A', 'Mock B', 'Review clinics'],
        lessons_ar: ['تجريبي أ', 'تجريبي ب', 'عيادات المراجعة'],
      },
      {
        title_en: 'Agile & Hybrid Pack',
        title_ar: 'حزمة الرشيق والهجين',
        duration_en: '240 questions',
        duration_ar: '240 سؤالًا',
        lessons_en: ['Scrum tells', 'Hybrid governance', 'Value delivery'],
        lessons_ar: ['علامات سكرم', 'حوكمة هجينة', 'تسليم القيمة'],
      },
    ],
    schedule_en: 'On-demand simulator. 90-day access from first launch.',
    schedule_ar: 'محاكٍ عند الطلب. وصول 90 يومًا من أول تشغيل.',
    modes: {
      simulator: {
        price: 120,
        original_price: 160,
        duration_en: '1,800+ Questions',
        duration_ar: '+1,800 سؤال',
        features_en: [
          '1,800+ original questions',
          'Two full 180-item exams',
          'Domain heatmaps',
          'Bilingual interface',
          '90-day access',
        ],
        features_ar: [
          '+1,800 سؤال أصلي',
          'امتحانان كاملان بـ 180 بندًا',
          'خرائط حرارية للنطاقات',
          'واجهة ثنائية اللغة',
          'وصول 90 يومًا',
        ],
      },
    },
  },
  {
    slug: 'pmp-mindset-core-file',
    category: 'materials',
    defaultMode: 'recorded',
    availableModes: ['recorded'],
    badge_en: 'Quick Summary',
    badge_ar: 'ملخص سريع',
    title_en: 'PMP® Mindset & Core File',
    title_ar: 'عقلية PMP® والملف الأساسي',
    subtitle_en: 'PDF + audio pocket guide for the week before the exam.',
    subtitle_ar: 'دليل جيب PDF وصوتي لأسبوع ما قبل الامتحان.',
    description_en:
      'The Core File is a distilled mindset pack: how PMI wants you to think, the 40 principles that decide close answers, and audio recaps you can play on commute. Not a full course — a last-mile companion.',
    description_ar:
      'الملف الأساسي حزمة عقلية مكثفة: كيف يريد PMI أن تفكّر، والمبادئ الأربعون التي تحسم الإجابات المتقاربة، ومراجعات صوتية لطريق العمل. ليست دورة كاملة — رفيق الميل الأخير.',
    price: 70,
    original_price: 70,
    currency: 'USD',
    rating: 4.75,
    students_count: 15440,
    duration_hours: 4,
    duration_label_en: 'PDF & Audio',
    duration_label_ar: 'PDF وصوتي',
    language_en: 'English & Arabic',
    language_ar: 'الإنجليزية والعربية',
    last_updated: '2026-02-14',
    cover_image: '/images/1.png',
    instructor_name: INSTRUCTOR.name_en,
    target_audience_en: [
      'Anyone sitting the PMP exam within 14 days',
      'Visual learners who prefer one-page maps',
      'Commuters who study by audio',
    ],
    target_audience_ar: [
      'أي شخص يدخل امتحان PMP خلال 14 يومًا',
      'المتعلمون البصريون الذين يفضّلون خرائط صفحة واحدة',
      'من يدرس صوتيًا أثناء التنقل',
    ],
    learning_outcomes_en: [
      'Internalize the PMI “correct” mindset under pressure',
      'Memorize high-yield principles as audio loops',
      'Use one-page maps for People, Process, and Business',
      'Walk into the exam with a 10-minute warm-up ritual',
    ],
    learning_outcomes_ar: [
      'استيعاب عقلية PMI الصحيحة تحت الضغط',
      'حفظ المبادئ عالية العائد كحلقات صوتية',
      'استخدام خرائط صفحة واحدة للأشخاص والعمليات والأعمال',
      'دخول الامتحان بطقس إحماء من 10 دقائق',
    ],
    curriculum: [
      {
        title_en: 'Mindset Manifesto',
        title_ar: 'بيان العقلية',
        duration_en: '40 pages',
        duration_ar: '40 صفحة',
        lessons_en: ['Servant default', 'Value over process', 'Ethics traps'],
        lessons_ar: ['الافتراض الخادم', 'القيمة فوق العملية', 'فخاخ الأخلاقيات'],
      },
      {
        title_en: 'Core Maps',
        title_ar: 'الخرائط الأساسية',
        duration_en: '12 pages',
        duration_ar: '12 صفحة',
        lessons_en: ['People map', 'Process map', 'Business map'],
        lessons_ar: ['خريطة الأشخاص', 'خريطة العمليات', 'خريطة الأعمال'],
      },
      {
        title_en: 'Audio Recaps',
        title_ar: 'المراجعات الصوتية',
        duration_en: '3 hours',
        duration_ar: '3 ساعات',
        lessons_en: ['Morning loop', 'Night loop', 'Exam-eve briefing'],
        lessons_ar: ['حلقة الصباح', 'حلقة الليل', 'إحاطة ليلة الامتحان'],
      },
    ],
    schedule_en: 'Self-paced PDF + 3 hours of audio. Instant download after checkout.',
    schedule_ar: 'PDF بالوتيرة الذاتية + 3 ساعات صوت. تحميل فوري بعد الدفع.',
    modes: {
      recorded: {
        price: 70,
        original_price: 90,
        duration_en: 'PDF & Audio',
        duration_ar: 'PDF وصوتي',
        features_en: [
          'Printable core PDF',
          '3-hour audio pack',
          'Exam-eve checklist',
          'Bilingual files',
          'Lifetime download',
        ],
        features_ar: [
          'ملف PDF أساسي للطباعة',
          'حزمة صوتية 3 ساعات',
          'قائمة ليلة الامتحان',
          'ملفات ثنائية اللغة',
          'تحميل مدى الحياة',
        ],
      },
    },
  },
];

export function getPublicCourse(slug) {
  return PUBLIC_CATALOG.find((course) => course.slug === String(slug)) || null;
}

export function localizeCatalogCourse(course, lang = 'en') {
  if (!course) return null;
  const ar = lang === 'ar';
  const modes = {};
  Object.entries(course.modes || {}).forEach(([key, mode]) => {
    modes[key] = {
      price: mode.price,
      originalPrice: mode.original_price,
      duration: ar ? mode.duration_ar : mode.duration_en,
      features: ar ? mode.features_ar : mode.features_en,
    };
  });

  return {
    id: course.id ?? null,
    slug: course.slug,
    category: course.category,
    defaultMode: course.defaultMode,
    availableModes: course.availableModes,
    badge: ar ? course.badge_ar : course.badge_en,
    title: ar ? course.title_ar : course.title_en,
    subtitle: ar ? course.subtitle_ar : course.subtitle_en,
    description: ar ? course.description_ar : course.description_en,
    price: course.price,
    originalPrice: course.original_price,
    currency: course.currency,
    rating: course.rating,
    studentsCount: course.students_count,
    durationHours: course.duration_hours,
    durationLabel: ar ? course.duration_label_ar : course.duration_label_en,
    language: ar ? course.language_ar : course.language_en,
    lastUpdated: course.last_updated,
    coverImage: course.cover_image,
    instructorName: ar ? INSTRUCTOR.name_ar : INSTRUCTOR.name_en,
    instructor: {
      name: ar ? INSTRUCTOR.name_ar : INSTRUCTOR.name_en,
      title: ar ? INSTRUCTOR.title_ar : INSTRUCTOR.title_en,
      photo: INSTRUCTOR.photo,
      trained: INSTRUCTOR.trained,
      countries: INSTRUCTOR.countries,
      credentials: ar ? INSTRUCTOR.credentials_ar : INSTRUCTOR.credentials_en,
      bio: ar ? INSTRUCTOR.bio_ar : INSTRUCTOR.bio_en,
    },
    targetAudience: ar ? course.target_audience_ar : course.target_audience_en,
    learningOutcomes: ar ? course.learning_outcomes_ar : course.learning_outcomes_en,
    curriculum: (course.curriculum || []).map((mod) => ({
      title: ar ? mod.title_ar : mod.title_en,
      duration: ar ? mod.duration_ar : mod.duration_en,
      lessons: ar ? mod.lessons_ar : mod.lessons_en,
    })),
    schedule: ar ? course.schedule_ar : course.schedule_en,
    modes,
    seo: {
      title: ar ? course.title_ar : course.title_en,
      description: ar ? course.subtitle_ar : course.subtitle_en,
    },
  };
}

export function localizeCatalog(lang = 'en') {
  return PUBLIC_CATALOG.map((course) => localizeCatalogCourse(course, lang));
}
